# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\workplace\PythonProject\Kilon1999\gui\ui\homeframe.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HomeFrame(object):
    def setupUi(self, HomeFrame):
        HomeFrame.setObjectName("HomeFrame")
        HomeFrame.resize(869, 540)

        self.retranslateUi(HomeFrame)
        QtCore.QMetaObject.connectSlotsByName(HomeFrame)

    def retranslateUi(self, HomeFrame):
        _translate = QtCore.QCoreApplication.translate
        HomeFrame.setWindowTitle(_translate("HomeFrame", "Frame"))
